### ISSUE TITLE
vits训练loss数值范围的问题

### ISSUE THREAD

**Issue by wgc7998** [wenet-e2e/wetts#125]
请问在训练过程中，判别器d-loss，生成器g-loss，特征feature-matching-loss，重建mel-loss，时长模块dur-loss，以及kl散度kl-loss的正常数值范围大致是多少，充分训练的模型，上述几个loss一般都保持在什么范围内呢，能不能提供一些参考数值，来判断模型是否训练正常，非常感谢～

**Comment by MaxMax2016** [comment]
![vits_loss](https://user-images.githubusercontent.com/16432329/214211716-5ab0db80-4855-4a27-9903-2607321e6bb5.png)
