### ISSUE TITLE
训练韵律预测模型一般需要多少数据量泛化性能好一些

### ISSUE THREAD

**Issue by Pydataman** [wenet-e2e/wetts#130]

**Comment by Pydataman** [comment]
@pengzhendong 
她一会儿夸这花厅风景好又敞亮，一会儿夸贺二太太会料理。
这条文本用韵律模型预测得出
她#1一会儿#1夸这#1花厅#1风景好#1又#1敞亮#3，一会儿#1夸贺#1二太太#1会#1料理#4。

尤其贺二太太这块会处理错误。


我看了这个项目韵律模型的实现方式，输入是分词后的结果？

**Comment by Pydataman** [comment]
后面还要有后处理

**Comment by masimeng1994** [comment]
请问有训练好的韵律模型吗？
