### ISSUE TITLE
baker推理结果问题

### ISSUE THREAD

**Issue by postmelone** [wenet-e2e/wetts#132]
您好，我在使用example/baker用例遇到了一些问题：
   模型已经训练到400k了，但是推理结果仍然会有部分词发音不准确，读错字，以及整体韵律上的问题，
   比如：
         老祖母#2以#1谋杀罪#1被#1收押#4。
	lao3 zu2 mu3 yi3 mou2 sha1 zui4 bei4 shou1 ya1
    这句话在合成时，“收押”的押会读成“收wa”，以及一些其他的读音发音问题，请问这些问题是vits中文TTS上普遍存在的吗？是什么问题造成的？因为我在vits的英文TTS上实验很少会出现此类问题。希望楼主解答一下，非常感谢！

**Comment by dyustc** [comment]
Sort of a newbie to TTS field, and I came across the same issue, not a very decent performance of the frontend part now, I think it's maybe due to the datasets used to finetune the bert model? Is this dataset size big enough? Or is g2pm( I found in the dataset download script) not a very reliable datasource?
![Uploading 截屏2023-04-27 12.01.23.png…]()

**Comment by pengzhendong** [comment]
> 您好，我在使用example/baker用例遇到了一些问题： 模型已经训练到400k了，但是推理结果仍然会有部分词发音不准确，读错字，以及整体韵律上的问题， 比如： 老祖母#2以#1谋杀罪#1被#1收押#4。 lao3 zu2 mu3 yi3 mou2 sha1 zui4 bei4 shou1 ya1 这句话在合成时，“收押”的押会读成“收wa”，以及一些其他的读音发音问题，请问这些问题是vits中文TTS上普遍存在的吗？是什么问题造成的？因为我在vits的英文TTS上实验很少会出现此类问题。希望楼主解答一下，非常感谢！

因为 ya1 (ia1) 是零声母，可能合成有些问题。你可以给零声母一个占位符，例如 `^ ia1`

**Comment by postmelone** [comment]
感谢回复，这个问题已经解决了，也是使用了占位符，上周我看到此项目中提供了新的baker的预训练权重，不过新给的预训练权重无法用于模型推理，原因是预训练的权重中token的embedding维度与model中的不一致，请问这个问题是否依旧存在？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wenet-e2e/wetts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月19日(星期一) 上午10:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wenet-e2e/wetts] baker推理结果问题 (Issue #132)





  
您好，我在使用example/baker用例遇到了一些问题： 模型已经训练到400k了，但是推理结果仍然会有部分词发音不准确，读错字，以及整体韵律上的问题， 比如： 老祖母#2以#1谋杀罪#1被#1收押#4。 lao3 zu2 mu3 yi3 mou2 sha1 zui4 bei4 shou1 ya1 这句话在合成时，“收押”的押会读成“收wa”，以及一些其他的读音发音问题，请问这些问题是vits中文TTS上普遍存在的吗？是什么问题造成的？因为我在vits的英文TTS上实验很少会出现此类问题。希望楼主解答一下，非常感谢！
  
因为 ya1 (ia1) 是零声母，可能合成有些问题。你可以给零声母一个占位符，例如 ^ ia1

**Comment by pengzhendong** [comment]
你用的配置文件是预训练模型压缩包里的？还是 examples 目录下的？我这边是跑过的，您方便提供一下日志吗？
