### ISSUE TITLE
HIFIGAN 1D to 2D疑问

### ISSUE THREAD

**Issue by masimeng1994** [wenet-e2e/wetts#136]
请问下，为什么hifigan的MPD的1D->2D是这样实现的呀？
`def forward(self, x):
        fmap = []

        # 1d to 2d
        b, c, t = x.shape
        if t % self.period != 0:  # pad first
            n_pad = self.period - (t % self.period)
            x = F.pad(x, (0, n_pad), "reflect")
            t = t + n_pad
        x = x.view(b, c, t // self.period, self.period)
`
![image](https://github.com/wenet-e2e/wetts/assets/24523981/abeddc99-e9ab-4f44-a077-9c1f718acd39)
从图上来看，比如【1,2,3,4,5,6】应该变成【【1,3,5】，【2,4,6】】嘛？

**Comment by robin1001** [comment]
把那个图倒过来，竖着看，不就是 [[1, 2] [3, 4], [5, 6]]
