### ISSUE TITLE
请问有没有考虑支持一下中英混合语音合成呢？

### ISSUE THREAD

**Issue by MarsMeng1994** [wenet-e2e/wetts#151]

**Comment by pengzhendong** [comment]
目前还没有质量较好的中英混训练数据，未来会基于标贝和 vctk 数据实现中英混语音合成。

**Comment by pengzhendong** [comment]
基于 baker 和 ljspeech 搞了一版，可以体验下：https://github.com/wenet-e2e/wetts/tree/main/examples/multilingual
