### ISSUE TITLE
请教如何用AISHELL3训练wetts的问题

### ISSUE THREAD

**Issue by ShangkunTu** [wenet-e2e/wetts#152]
大大您好，我似乎没看到您在工程里有关于如何用AISHELL3去实现工程的PIPLINE，可能其他大佬们一看都知道如何去部署，但是我刚接触这些问题，是初学者，不知道如何去训练，同时又听说您的团队做的wetts非常的先进，很想尝试学习一下，您方便提供一下关于如何用AISHELL3去部署wetts的Reademe吗？感谢感谢！

**Comment by pengzhendong** [comment]
你说的是模型训练？还是模型推理部署？

**Comment by ShangkunTu** [comment]
> 你说的是模型训练？还是模型推理部署？

模型训练部分，没接触过工程化的东西，找不到训练的pipline和入口，不知道如何动手，谢谢佬！

**Comment by pengzhendong** [comment]
直接跑这个脚本：https://github.com/wenet-e2e/wetts/blob/main/examples/aishell-3/run.sh
