### ISSUE TITLE
实验的config和代码是不是没有同步修改？

### ISSUE THREAD

**Issue by a122760** [wenet-e2e/wetts#191]
很多.json里面（比如[aishell3/configs/v1.json](https://github.com/wenet-e2e/wetts/blob/main/examples/aishell-3/configs/v1.json)），我看之前的[commits](https://github.com/wenet-e2e/wetts/commit/b6fa3f95be6f65eacd802914640be0828be6ded7)把mel_fmin和mel_fmax删掉了，但是代码https://github.com/wenet-e2e/wetts/blob/f55a843eef6915d87050f9573bcbebfd289441f9/wetts/vits/data_utils.py#L26C25-L26C25 中现在是需要这俩参数的，没有提供默认值。

**Comment by Shengqiang-Li** [comment]
这个bug已经修复了
