### ISSUE TITLE
Does there any speed improvement compare with original version?

### ISSUE THREAD

**Issue by jinfagang** [wenet-e2e/wetts#34]
Does there any speed improvement compare with original version?

**Comment by dtx525942103** [comment]
@jinfagang 偶遇

**Comment by jinfagang** [comment]
@unrea1-sama thanks. Does it will trying implement a C++ version in the future? Inference via onnx or other way.

**Comment by unrea1-sama** [comment]
Yes.

**Comment by jinfagang** [comment]
Hoping for it! Does it has plan on using which forward framework to inference?

**Comment by unrea1-sama** [comment]
Libtorch and ONNX are in our plan.
