### ISSUE TITLE
mfa train error

### ISSUE THREAD

**Issue by AlanYs** [wenet-e2e/wetts#40]
（1）on line 54 of examples/aishell3/run.sh，mfa train ...
I got an error :

ArgumentError: Got more arguments for output_paths than 2: ['fastspeech2/mfa_pronounciation_dict.txt', 'fastspeech2/mfa/mfa_model.zip', 'fastspeech2/TextGrid']

I found that the format of this command（mfa train） seems to be different than usual，maybe i'm a newbie.

And I don't have fastspeech2/mfa/mfa_model.zip either

(2) on line 29 of aishell3/local/prepare_data_list.py ,maybe "type=str"

**Comment by robin1001** [comment]
What's the version of your MFA? please refer https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/workflows/train_acoustic_model.html#mfa-train

**Comment by unrea1-sama** [comment]
1. Please run `conda activate wetts; conda list montreal-forced-aligner` to see the version for mfa. We have tested on 2.0.0rc9 and 2.0.1 and everything is fine.
2. This is a typo and we will fix it. Thankyou!

**Comment by cwk777** [comment]
Version 2.0.1 is ok, Thank you. I used version 2.0.0b9 before

**Comment by AlanYs** [comment]
Version 2.0.1 is ok , Thank you ,I used version 2.0.0b9 before
