### ISSUE TITLE
Design Principles of PaddleSpeech pinyin lexicon

### ISSUE THREAD

**Issue by yt605155624** [wenet-e2e/wetts#49]
[g2p.md](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/topic/frontend/g2p.md)

So, if you want to use common G2P tools in text frontend such as pypinyin and g2pM, you should pay attention to the following rules:

```python
for c, v in zip(orig_initials, orig_finals):
    if re.match(r'i\d', v):
        if c in ['z', 'c', 's']:
            v = re.sub('i', 'ii', v)
        elif c in ['zh', 'ch', 'sh', 'r']:
            v = re.sub('i', 'iii', v)
```

https://github.com/PaddlePaddle/PaddleSpeech/blob/0fa3fdb9ee89ca399b0f63ef2117c6370dc1f33d/paddlespeech/t2s/frontend/zh_frontend.py#L118

:)

**Comment by robin1001** [comment]
That's very kind of you. Thanks a lot.
