### ISSUE TITLE
run   wetts/bin/train.py fastspeech have problem

### ISSUE THREAD

**Issue by tangzhimiao** [wenet-e2e/wetts#65]
Why this problem arises？

../aten/src/ATen/native/cuda/Indexing.cu:650: indexSelectSmallIndex: block: [1,0,0], thread: [24,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:650: indexSelectSmallIndex: block: [1,0,0], thread: [25,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:650: indexSelectSmallIndex: block: [1,0,0], thread: [26,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:650: indexSelectSmallIndex: block: [1,0,0], thread: [27,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:650: indexSelectSmallIndex: block: [1,0,0], thread: [28,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:650: indexSelectSmallIndex: block: [1,0,0], thread: [29,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:650: indexSelectSmallIndex: block: [1,0,0], thread: [30,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:650: indexSelectSmallIndex: block: [1,0,0], thread: [31,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by unrea1-sama** [comment]
1. You can enable CUDA_LAUNCH_BLOCKING=1 when running `python wetts/bin/train.py` to see more debugging information.
2. You can check if your CUDA version matches your torch version.
3. You can check if the shape of your input match required shape when tensors are passed to fastspeech2.

**Comment by tangzhimiao** [comment]
ok,  where set available cuda number in wetts/bin/fastspeech2_train.py?
I dont see any one , Is set  that os.environ['CUDA_VISIBLE_DEVICES'] = "0,1" use gpu training model?

**Comment by unrea1-sama** [comment]
Right now distributed training is not supported. Setting `os.environ['CUDA_VISIBLE_DEVICES'] = "0,1"` or run `CUDA_VISIBLE_DEVICES=0,1 python wetts/bin/train.py ...` can explicitly set GPU.
