### ISSUE TITLE
when calculate iph f1, remove #4 will be more accurate

### ISSUE THREAD

**Issue by lesswrongzh** [wenet-e2e/wetts#72]
because ending label must be `#4`

https://github.com/wenet-e2e/wetts/blob/60c202b2e9c3bf63de82bd0849c4e2052daa55b4/wetts/frontend/test_prosody.py#L80-L81

should change to `label[:-1], pred[:-1]`, or don't take `#4` into acount

**Comment by yqli2420** [comment]
Thanks, the test_prosody.py has been updated  https://github.com/wenet-e2e/wetts/pull/73

**Comment by WhiteFu** [comment]
为什么计算PPH f1的时候，要把IPH的值也算进去呢
